### ISSUE TITLE
Make phing version configurable

### ISSUE THREAD

**Issue by siad007** [phingofficial/phing-github-action#1]
Current phing version should be configurable
https://github.com/phingofficial/phing-github-action/blob/d8d9ded35231cbafd3f6af8295664db18fe7c306/Dockerfile#L8

Add a new `version` parameter to the workflow section:
```yaml
    steps:
        - uses: actions/checkout@v2
        - name: Phing Build
          uses: phingofficial/phing-github-action@main
          with:
              version: 3.0.0-alpha4
```
